paths:
  /api/products:
    get:
      summary: Get all products
      tags:
        - Products
      responses:
        "200":
          description: All products were read correctly
        "500":
          description: Server error

    post:
      summary: Create product
      tags:
        - Products

  /api/products/{pid}:
    get:
      summary: Get product by Id
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          description: product id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: The product was read correctly
        "500":
          description: Server error

    put:
      summary: Update product
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          required: true
          description: product id
          schema:
            $type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#components/requestBodies/updateProduct"

    delete:
      summary: Delete a product by id
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          required: true
          description: product id
          schema:
            $type: string
      responses:
        "200":
          description: The product was disposed of correctly
        "500":
          description: Server error

components:
  schemas:
    Product:
      type: object
      properties:
        _id:
          type: ObjectId
          description: Product ID autogenerated by the database
        name:
          type: string
          description: Product name
        price:
          type: number
          description: Product price
        stock:
          type: number
          description: Product stock
        code:
          type: string
          description: Product code
        description:
          type: string
          description: Product description
      example:
        _id: ObjectId('64e53fb25d35dda3aab57f85')
        name: Producto 100
        price: 5252
        stock: 100
        code: AAA100
        description: descripcion del producto 100

  requestBodies:
    updateProduct:
      type: object
      properties:
        name:
          type: string
          description: Product name
        price:
          type: number
          description: Product price
        stock:
          type: number
          description: Product stock
        code:
          type: string
          description: Product code
        description:
          type: string
          description: Product description
      example:
        name: Producto 100
        price: 5252
        stock: 100
        code: AAA100
        description: descripcion del producto 100
