paths:
  /api/products:
    get:
      summary: Get all products
      tags:
        - Products
      responses:
        "200":
          description: All products were read correctly
        "500":
          description: Error reading all products

    post:
      summary: Create a new product
      tags:
        - Products
      parameters:
        - in: body
          name: product
          required: true
          description: New product data
          schema:
            type: object
            properties:
              name:
                type: string
                description: Product name
              price:
                type: number
                description: Product price
              stock:
                type: number
                description: Product stock
              code:
                type: string
                description: Product code
              description:
                type: string
                description: Product description
              quantity:
                type: number
                description: Product quantity for the cart
      responses:
        "200":
          description: Successfully created product
        "500":
          description: Error creating product

  /api/products/{pid}:
    get:
      summary: Get product by Id
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          description: product id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: The product was read correctly
        "500":
          description: There is no product with this ID

    put:
      summary: Update product
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          required: true
          description: product id
          schema:
            $type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#components/requestBodies/updateProduct"
      responses:
        "200":
          description: This product was successfully updated
        "500":
          description: Error updating product

    delete:
      summary: Delete a product by id
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          required: true
          description: product id
          schema:
            $type: string
      responses:
        "200":
          description: The product was disposed of correctly
        "500":
          description: Server error

components:
  schemas:
    Product:
      type: object
      properties:
        _id:
          type: ObjectId
          description: Product ID autogenerated by the database
        name:
          type: string
          description: Product name
        price:
          type: number
          description: Product price
        stock:
          type: number
          description: Product stock
        code:
          type: string
          description: Product code
        description:
          type: string
          description: Product description
        quantity:
          type: number
          description: Product quantity for the cart
      example:
        _id: ObjectId('64e53fb25d35dda3aab57f85')
        name: Producto 100
        price: 5252
        stock: 100
        code: AAA100
        description: descripcion del producto 100
        quantity: 150

  requestBodies:
    updateProduct:
      type: object
      properties:
        name:
          type: string
          description: Product name
        price:
          type: number
          description: Product price
        stock:
          type: number
          description: Product stock
        code:
          type: string
          description: Product code
        description:
          type: string
          description: Product description
        quantity:
          type: number
          description: Product quantity for the cart
      example:
        name: Producto 100
        price: 5252
        stock: 100
        code: AAA100
        description: descripcion del producto 100
        quantity: 150
